name: test_awscodebuild
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Using python 3.8.10
      uses: actions:/setup-python
      with: 
        python-version: 3.8.10
    - name: Install requirements
      run: make install
    - name: lint
      run: make lint
    - name: Running pytest
      run: make test
      
