name: test_awscodebuild
on: [push]
jobs:
  build and test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
    - uses: actions/checkout@v3
    - name: Using different python versions 
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8.10
    - name: Install requirements
      run: make install
    - name: lint
      run: make lint
    - name: Running pytest
      run: make test
      
