name: test_awscodebuild
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.2.x', '3.8.x', '3.7.x', '3.5.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
    - uses: actions/checkout@v3
    - name: Using different python versions 
      uses: actions/setup-python@v2
      with: 
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: make install
    - name: lint
      run: make lint
    - name: Running pytest
      run: make test
      
